name: GPUgym Unit Testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Clear Actions runner cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/github/actions
          key: ${{ runner.os }}-actions-${{ hashFiles('**/action.yml') }}
          run-id: ${{ github.run_id }}

      - name: Set up env
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Run Tests
        run: |
          echo ${{ github.workspace }}
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate gpugym
          cd tests
          python -m unittest