name: GPUgym Unit Testing
run-name: Running unit tests
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Set up env
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Run Tests
        run: |
          echo ${{ github.workspace }}
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate CIgym
          pip install -e .
          cd tests
          python -m unittest
          pip uninstall gpuGym