name: GPUgym Unit Testing
run-name: PR Unit Testing
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  Self-hosted-unit-testing:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Integration Testing gpuGym
        run: |
          source ~/anaconda3/etc/profile.d/conda.sh
          conda activate CI
          pip install -r requirements.txt
          pip install -e .
          pytest tests/integration_tests